name: Update Changelog

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install dependencies
        run: bundle install

      - name: Update CHANGELOG.md
        run: bundle exec rake update_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push changes
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/tags/}
          git config --global user.name 'github-actions.bot'
          git config --global user.email 'github-actions.bot@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for $BRANCH_NAME"
          git push origin HEAD:$BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
